---

- name: copy crowd.properties
  template:
    src: crowd.properties
    dest: "{{ atlassian_confluence_home }}/crowd.properties"
    owner: "{{ atlassian_confluence_user }}"
    group: "{{ atlassian_confluence_group }}"
    mode: "0640"
    force: no
  tags:
    - atlassian-confluence

- name: adjusing crowd properties / server url
  lineinfile:
    dest: "{{ atlassian_confluence_home }}/crowd.properties"
    regexp: "^\\s*{{ item.name }}\\s+"
    line: "{{ item.name }}\t\t{{ item.value }}"
    insertafter: EOF
  with_items:
    - { "name": "application.login.url", "value": "{{ atlassian_confluence_crowd_url }}/console/"}
    - { "name": "crowd.server.url", "value": "{{ atlassian_confluence_crowd_url }}/services/"}
    - { "name": "crowd.base.url", "value": "{{ atlassian_confluence_crowd_url }}/"}
  tags:
    - atlassian-confluence

- name: adjusing crowd properties / server others
  lineinfile:
    dest: "{{ atlassian_confluence_home }}/crowd.properties"
    regexp: "^\\s*{{ item.name }}\\s+"
    line: "{{ item.name }}\t\t{{ item.value }}"
    insertafter: EOF
  with_items: "{{ atlassian_confluence_crowd_properties|default([]) }}"
  tags:
    - atlassian-confluence

- name: change seraph-config.xml authentificator
  xml:
    file: "{{ atlassian_confluence_dir }}/confluence/WEB-INF/classes/seraph-config.xml"
    xpath: /security-config/authenticator
    ensure: present
    attribute: class
    value: com.atlassian.confluence.user.ConfluenceCrowdSSOAuthenticator
  tags:
    - atlassian-confluence

- name: change seraph-config.xml others
  xml:
    file: "{{ atlassian_confluence_dir }}/confluence/WEB-INF/classes/seraph-config.xml"
    xpath: "{{ item.xpath }}"
    attribute: "{{ item.attribute|default(omit) }}"
    ensure: "{{ item.ensure|default('present') }}"
    value: "{{ item.value|default(omit) }}"
  with_items: "{{ atlassian_confluence_seraph_config }}"
  tags:
    - atlassian-confluence


- name: catalina enviroment settings for CrowdSSO (1)
  lineinfile:
    dest: "{{ atlassian_confluence_dir }}/bin/setenv.sh"
    regexp: '^CATALINA_OPTS_CROWDSSO='
    line: 'CATALINA_OPTS_CROWDSSO="-Dcrowd.properties={{ atlassian_confluence_home }}/crowd.properties"'
    insertbefore: '^CATALINA_OPTS'
  tags:
    - atlassian-confluence

- name: catalina enviroment settings for CrowdSSO (2)
  lineinfile:
    dest: "{{ atlassian_confluence_dir }}/bin/setenv.sh"
    regexp: '^CATALINA_OPTS="\$\{CATALINA_OPTS_CROWDSSO\} '
    line: 'CATALINA_OPTS="${CATALINA_OPTS_CROWDSSO} ${CATALINA_OPTS}"'
    insertbefore: '^export CATALINA_OPTS'
  tags:
    - atlassian-confluence
