---
- name: download atlassian-confluence tar.gz
  get_url:
    url: "{{ download_url }}"
    dest: "{{ download_tmp }}"
    validate_certs: no
    force: no

- name: extract the atlassian-confluence tar.gz
  unarchive:
    copy: no
    creates: "{{ atlassian_confluence_dir }}"
    owner: root
    group: root
    src: "{{ download_tmp }}"
    dest: "{{ atlassian_confluence_basedir }}"

- name: fix directory permissions
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items:
    - {path: "{{ atlassian_confluence_dir }}/temp",
       owner: "{{ atlassian_confluence_user }}",
       group: "{{ atlassian_confluence_group }}"}
    - {path: "{{ atlassian_confluence_dir }}/work",
       owner: "{{ atlassian_confluence_user }}",
       group: "{{ atlassian_confluence_group }}"}
    - {path: "{{ atlassian_confluence_dir }}/logs",
       owner: "{{ atlassian_confluence_user }}",
       group: "{{ atlassian_confluence_group }}"}
